package com.projectnublar.mod;

import com.projectnublar.mod.proxy.CommonProxy;

import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.VERSION)
public class Main {
	
	@Instance(Reference.MOD_ID)
	public static Main instance;
	
	@SidedProxy(clientSide = Reference.CLIENT_PROXY_CLASS, serverSide = Reference.SERVER_PROXY_CLASS)
	public static CommonProxy proxy;
	
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		
		proxy.preInit(event);
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.name = EnumChatFormatting.AQUA + Reference.MOD_NAME;
		data.description = "Official Project Nublar";
		data.credits = "The Project Nublar Modding Team";
		data.modId = Reference.MOD_ID;
		//data.url = "http://minecraft.curseforge.com/projects/shadowcreatures-mod";
		data.version = Reference.VERSION;
		data.authorList.add("UpcraftLP");
		data.logoFile = "assets/"+ Reference.MOD_ID + "/textures/gui/logo.png";
		
	}

	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		proxy.init(event);
		
	}
	
	@EventHandler
	public void PostInit(FMLPostInitializationEvent event)
	{
		proxy.postInit(event);
	}
	
	@EventHandler
	public void worldLoad(FMLServerStartingEvent event)
	{
		//ShadowCommands.init(event);
		
	}
}
